version: "3.8"

services:	
  db:
    image: postgres:14.13
    container_name: db
    environment:
      POSTGRES_USER: worker
      POSTGRES_PASSWORD: worker
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U worker -d app"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default

  app:
    build:
      context: .
    container_name: app
    ports:
      - "8001:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DJANGO_DB_HOST: "db"
      DJANGO_DB_NAME: "app"
      DJANGO_DB_USER: "worker"
      DJANGO_DB_PASS: "worker"
      DJANGO_DB_PORT: 5432
      DJANGO_DEBUG: "False"
    networks:
      - default
      
volumes:
  pg_data:

networks:
  default:
    driver: bridge
